### ISSUE TITLE
Fatal error: Missing method exception

### ISSUE THREAD

**Issue by jaum20** [endrl/jellyfin-plugin-edl#3]
tried to run the action, got error:

[2024-11-19 14:32:55.719 -03:00] [ERR] Error executing Scheduled Task
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<MediaBrowser.Model.MediaSegments.MediaSegmentDto>> MediaBrowser.Controller.IMediaSegmentManager.GetSegmentsAsync(System.Guid, System.Collections.Generic.IEnumerable`1<Jellyfin.Data.Enums.MediaSegmentType>)'.
   at Jellyfin.Plugin.EdlManager.CreateEdlTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.EdlManager.CreateEdlTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by thubble** [comment]
Looks like the ABI changed in Jellyfin 10.10.2: https://github.com/jellyfin/jellyfin/commit/c08d1d5b7f45b41ef200e9604fa38096c1560a85

It's a trivial change, hopefully just needs a recompile.

**Comment by astubbs** [comment]
@jaum20 would you please mind editing your issue's title to reflect the error? I suggest "Fatal error: Missing method exception"

**Comment by jaum20** [comment]
I think my problem was jellyfin haven’t permissions to write in the media ditectory.  After perform `sudo chmod -R 775 /path/to/library` it is working fine. But I am using this version: https://github.com/intro-skipper/jellyfin-plugin-edl

**Comment by zerocoolie** [comment]
I previously used https://github.com/intro-skipper/intro-skipper (which pointed me towards this plugin after the developers removed the EDL creation function). 

Intro Skipper had no issues writing the EDL files to my library folders, which are Synology NFS shares mounted to the Ubuntu host OS and presented to the jellyfin container as volumes in docker-compose. For this reason, I don't think the issue I'm seeing is a permissions one.

I'm still getting a fail on the Scheduled Task with these log lines:
`[11:43:24] [ERR] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task"1<System.Collections.Generic.IEnumerable"1<MediaBrowser.Model.MediaSegments.MediaSegmentDto>> MediaBrowser.Controller.IMediaSegmentManager.GetSegmentsAsync(System.Guid, System.Collections.Generic.IEnumerable"1<Jellyfin.Data.Enums.MediaSegmentType>)'.
   at Jellyfin.Plugin.EdlManager.CreateEdlTask.ExecuteAsync(IProgress"1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.EdlManager.CreateEdlTask.ExecuteAsync(IProgress"1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[11:43:24] [INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Create EDL Failed after 0 minute(s) and 0 seconds`

UPDATE: I manually installed this version https://github.com/intro-skipper/jellyfin-plugin-edl/releases/tag/0.3.1-0b873bc and EDLs were created successfully!
